language: python
dist: xenial
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x

matrix:
  include:
    - python: '2.7'
      env:
        - TOXENV=py27
    - python: '3.5'
      env:
        - TOXENV=py35
    - python: '3.6'
      env:
        - TOXENV=py36
    - python: '3.7'
      env:
        - TOXENV=py37
    - python: 'nightly'
      env: TOXENV=py38

install:
  - sudo apt-get install fonts-ipafont-gothic libjpeg8-dev libfreetype6-dev
  - pip install -U docutils tox

script:
  - tox -- -v
